---
kind: pipeline
type: kubernetes
name: Public-Registry

steps:
  - name: docker-build-npd
    image: plugins/docker
    settings:
      repo: supporttools/public-registry-router
      tags:
        - pr-${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      context: ./router/
    when:
      branch:
      - feature/*

  - name: docker-build-prd
    image: plugins/docker
    settings:
      repo: supporttools/public-registry-router
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      context: ./router/
    when:
      branch:
      - main
