apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
  name: registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-nfs
